### ISSUE TITLE
Use Text instead of String

### ISSUE THREAD

**Issue by nikita-volkov** [Gabriel439/Haskell-Errors-Library#24]
What do you think about switching to `EitherT Text` instead of `EitherT String` throughout the library?

**Comment by expipiplus1** [comment]
Any progress on this?

**Comment by Gabriel439** [comment]
Alright, it's happening.  I opened up a PR for this here: https://github.com/Gabriel439/Haskell-Errors-Library/pull/48

Feel free to comment there.  If nobody objects after a week then I'll merge and push to Hackage
