### ISSUE TITLE
A proposal on monad which prohibits exceptions

### ISSUE THREAD

**Issue by nikita-volkov** [Gabriel439/Haskell-Errors-Library#25]
Exceptions are evil, right? However yet there is no standard way of protecting from them when dealing with `IO`. The "errors" library proclaims the `EitherT e IO r` idiom as an alternative to exception-based control-flow, however it does not protect the user from still getting the exceptions thrown by the wrapped `IO` computation. I propose defining a new monad, which will serve as a general replacement of `IO`, to solve that problem. Following is a sketch of my idea:

```haskell
module EIO (EIO, liftIO, liftIO') where

-- |
-- A monad for 'IO' computations, 
-- which prohibits exceptions in favour of a cleaner 'EitherT'-based approach.
-- 
-- When executed it returns a computation, 
-- which has all the exceptions wrapped by the 'EitherT' monad.
-- It however rethrows the async exceptions of the @base@ package
-- for the reasons of general compatibility with the platform.
-- 
-- Note that it intentionally does not derive 'MonadIO'.
-- Instead it provides specialized 'liftIO' and 'liftIO'' functions.
newtype EIO e r = EIO { run :: EitherT e IO r } deriving (Functor, Applicative, Monad)

-- |
-- A specialized version of @MonadIO.'Control.Monad.IO.Class.liftIO'@, 
-- which catches exceptions and forces to adapt them to the @EIO@ monad.
-- It catches all exceptions, except for asynchronous ones of the @base@ package.
liftIO :: (SomeException -> e) -> IO r -> EIO e r
liftIO f = EIO . fmapLT f . syncIO

-- |
-- A version of 'liftIO' for cases 
-- when any exception thrown from the computation to be lifted 
-- is considered a bug.
liftIO' :: IO r -> EIO e r
liftIO' = liftIO $ error "An IO action lifted to EIO throws an exception"
```

Now, of course, it is implied that this API should be extended with adaptations of many functions of the `errors` library or be otherwise provided with support for them. 

I am not sure whether this proposal is fit for the purposes of the "errors" library. Possibly it should be developed as a separate project. However I want to discuss it with you and get you involved.

**Comment by singpolyma** [comment]
But, either way, same or different, would be nice to see something make it into 2.0 which I gather is coming soon?

**Comment by Gabriel439** [comment]
I will add this after the transition to 2.0

**Comment by singpolyma** [comment]
Ok

**Comment by singpolyma** [comment]
Happy new year!  Wondering if there's still interest in this :)

**Comment by Gabriel439** [comment]
Yes!  I will try to get to this soon.  Thanks for the reminder

**Comment by nikita-volkov** [comment]
BTW, @singpolyma please release the update, which we've discussed on your tracker.

**Comment by Gabriel439** [comment]
So I was doing a first pass at implementing this and realized that the use of `UnexceptionalIO` does cause one issue, which is that there is no `mtl`-style type class for the `UnexceptionalIO` monad.  I ran into this issue when attempting to generalize `tryIO`, whose current type signature looks like this:

```haskell
tryIO :: MonadIO m => IO a -> ExceptT Ex.IOException m a
```

@singpolyma Would you consider adding such a class?  If you do, I might suggest naming the class `Unexceptional`, so then the type of `tryIO` would be:

```haskell
tryIO :: Unexceptional m => IO a -> ExceptT IOException m a
```

**Comment by singpolyma** [comment]
so, it would be:

    class Unexceptional m where
        liftUIO :: UIO a -> m a

    instance Unexceptional IO where
        liftUIO = runUnexceptionalIO

and similar?  I'll do that, as well as the default-name-to-UIO discussed previously

**Comment by singpolyma** [comment]
please check that my current master works for you and then I will release it

**Comment by Gabriel439** [comment]
Alright, this worked great!  I'll upload this to Hackage tomorrow if nobody has any remaining objections

**Comment by singpolyma** [comment]
Looks good!  I've put 0.3.0 for unexceptionalio on hackage

**Comment by nikita-volkov** [comment]
Cool! :)

**Comment by Gabriel439** [comment]
Alright, this is on Hackage as `errors-2.1.0`
