### ISSUE TITLE
EitherT vs ExceptT

### ISSUE THREAD

**Issue by Gabriel439** [Gabriel439/Haskell-Errors-Library#32]
As many people know, `transformers-0.4.0.0` added the `ExceptT` type, which is like `EitherT`, but with a different name.  This raises the question for this library: should `errors` switch to `ExceptT` or not?

Advantages of switching to `ExceptT`:

* Smaller dependency graph
* Less fragmentation of the error-handling ecosystem (standardizing on `ExceptT`)

Disadvantages:

* Creates work for downstream libraries (See the full list here: http://packdeps.haskellers.com/reverse/errors)

My personal preference is to switch to `ExceptT`, however I would like to solicit feedback on how painful this would be for downstream libraries.

**Comment by mightybyte** [comment]
Hmmm, too bad I'm late to the game on this thread.  The ship has probably already sailed, but I actually think that the type alias would have been a good idea to ease the migration.  I agree that it would not be good if the intent was to keep it around indefinitely, but as a transitional step I think it would have been quite useful.  Oh well.
