### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by voidzero** [Gabriel439/Haskell-Errors-Library#35]
Hello, non-academic Haskell n00b here. Can I find examples somewere that explain how to use this library? Hope you don't mind me asking.

**Comment by Gabriel439** [comment]
Are you familiar with checked exceptions?  The four predominant Haskell idioms for checked exceptions (ignoring type classes) are:

* `Maybe`
* `Either`
* `MaybeT`
* `ExceptT`

This library contains lots of utilities for working with and converting between the above four types

**Comment by voidzero** [comment]
Oops, your reply fell off my radar. Yes, I think those are useful. I don't yet understand how to make use of ExceptT, but I am looking into transformers and learning. So I will probably be able to find my way. Thanks for replying. :+1:

**Comment by Gabriel439** [comment]
You're welcome!
