### ISSUE TITLE
Monadic maybe combinators

### ISSUE THREAD

**Issue by andrewthad** [Gabriel439/Haskell-Errors-Library#36]
This is a function that I copy around all the time:

    whenMaybe :: Applicative m => Maybe a -> (a -> m ()) -> m ()
    whenMaybe may g = case may of
      Just a  -> g a
      Nothing -> return ()

Would you accept a PR adding it to Control.Error.Util?

**Comment by Gabriel439** [comment]
This already exists in the standard libraries as `Data.Foldable.for_`, which has this type:

```haskell
for_ :: (Foldable t, Applicative f) => t a -> (a -> f b) -> f ()
```

... when you specialize `t` to `Maybe` (which implements `Foldable`), you get the type that you are looking for:

```haskell
for_ :: Applicative f => Maybe a -> (a -> f b) -> f ()
```

**Comment by andrewthad** [comment]
Oh my goodness! That makes me so happy.

**Comment by Gabriel439** [comment]
:)
