### ISSUE TITLE
Utilities for hard errors?

### ISSUE THREAD

**Issue by jml** [Gabriel439/Haskell-Errors-Library#40]
Exceptions are evil, sure, but it's good to have good errors when you make programming mistakes that the compiler can't catch. I wrote some helpers to do this—https://github.com/jml/pretty-error/—but I think they'd be better placed in a library like this one. 

Would you consider adding such functions to errors?

PS. I really love this package, thank you for maintaining it.

**Comment by Gabriel439** [comment]
This library avoids exporting partial functions, so I can't accept these.  Sorry  :(

I appreciate the request, though, and if I were you I would consider submitting these to the `safe` library which does provide partial `assert`-style functions

**Comment by jml** [comment]
Thanks!
