### ISSUE TITLE
transformers-0.6

### ISSUE THREAD

**Issue by nomeata** [Gabriel439/Haskell-Errors-Library#42]
Hi,

I see a few package building failures on travis of a package of mine, and it seems that your upper bound on transformers (`<0.5`) might be the cause. Now that transformers 0.6 is out there, would you mind including it?

Thanks,
Joachim

**Comment by Gabriel439** [comment]
I will bump the upper bound shortly!  Hopefully I will get to this tonight, but it may be up to a few days before I can do this.

**Comment by Gabriel439** [comment]
Alright, this is fixed.  Is it alright if I go ahead and upload this to Hackage?

**Comment by nomeata** [comment]
Are you asking me? It’s your package, so it’s your call. From my side, though: Yes, of course! :-)

**Comment by Gabriel439** [comment]
Alright, this is up on Hackage as `errors-2.1.2`
