### ISSUE TITLE
fmapLT is basically withExceptT

### ISSUE THREAD

**Issue by Profpatsch** [Gabriel439/Haskell-Errors-Library#44]
Except that `withExceptT` has less requirements:

```haskell
withExceptT :: Functor m => (e -> e') -> ExceptT e m a -> ExceptT e' m a
fmapLT      :: Monad   m => (a -> b ) -> ExceptT a m r -> ExceptT b  m r
```

**Comment by Gabriel439** [comment]
I think it's fine if `errors` exports two functions that do the same thing.  There are other examples of this in the library like all the `MonadPlus` functions in `Control.Error.Safe` are generalized versions of the functions re-exported from the `Safe` library

**Comment by Profpatsch** [comment]
Hm, in that case wouldn’t it make sense to redefine `fmapLT = withExceptT`? This way you can have the more general type and still use the name symmetry.

**Comment by Gabriel439** [comment]
I don't define `withExceptT`.  It's re-exported by default from `Control.Monad.Trans.Except` from `transformers`

**Comment by Gabriel439** [comment]
Oh sorry, I misunderstood your comment and read it backwards.  Yeah, I could do that
