### ISSUE TITLE
Operator precedence of ?:

### ISSUE THREAD

**Issue by dbaynard** [Gabriel439/Haskell-Errors-Library#49]
Hello,

Currently `?: :: Maybe a -> a -> a` has no declared precedence. Might I suggest the same as `$`, `$!` and `seq`, at
```haskell
infixr 0 ?:
```
?

That means `?:` plays nicely with level 1 `=<<` and `>>=`, in addition to other operators that may affect the `Maybe a`, and also plays nicely with `$`, as in the (trivial) example:

```haskell
(*2) $ pure =<< Just 1 ?: 0
```

**Comment by Gabriel439** [comment]
Sounds good to me!  I put up #50 to fix this.  Let me know if that looks good to you

**Comment by dbaynard** [comment]
It does. Do you consider this a breaking change? If so it may be worth considering other operators, too.

**Comment by Gabriel439** [comment]
I don't consider this a breaking change, so don't worry
